# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-08-10 16:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_no', models.CharField(max_length=65)),
                ('city', models.CharField(max_length=65)),
                ('state', models.CharField(max_length=65)),
                ('pincode', models.CharField(max_length=65)),
                ('country', models.CharField(max_length=65)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.PositiveIntegerField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=5)),
                ('profile_pic', models.ImageField(default='default.jpg', upload_to='profile_pic')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('permanent_address_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permanent_address_city', to='employeeapp.Address')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usermodel', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
